// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PlataformaEficienciaEnergetica.Data;

#nullable disable

namespace PlataformaEficienciaEnergetica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlataformaEficienciaEnergetica.Models.DadosEnergia", b =>
                {
                    b.Property<int>("DadosEnergiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DadosEnergiaId"));

                    b.Property<double>("ConsumoTotal")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PredioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DadosEnergiaId");

                    b.HasIndex("PredioId");

                    b.ToTable("DadosEnergia");
                });

            modelBuilder.Entity("PlataformaEficienciaEnergetica.Models.Predio", b =>
                {
                    b.Property<int>("PredioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredioId"));

                    b.Property<double>("ConsumoEnergetico")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double?>("UsoEnergiaRenovavel")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("PredioId");

                    b.ToTable("Predios");
                });

            modelBuilder.Entity("PlataformaEficienciaEnergetica.Models.DadosEnergia", b =>
                {
                    b.HasOne("PlataformaEficienciaEnergetica.Models.Predio", "Predio")
                        .WithMany("DadosEnergia")
                        .HasForeignKey("PredioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predio");
                });

            modelBuilder.Entity("PlataformaEficienciaEnergetica.Models.Predio", b =>
                {
                    b.Navigation("DadosEnergia");
                });
#pragma warning restore 612, 618
        }
    }
}
